& "$PSScriptRoot\..\gitmodules\mod-installer\build_all.ps1" `
  -Version "2.0.0" `
  -PreReleaseVersion "beta.1" `
  -OutputFilePrefix "Halloween_Redux" `
  -ModName "Halloween HL2: Pumpkin Night (Redux)" `
  -ModFolder "Halloween HL2 PN" `
  -ModFilesPath "$PSScriptRoot\..\game" `
  -ModBaseFilesUrl "https://github.com/HL2-Mods-Legacy-Project/hl2-legacy-registry/releases/download/halloween-redux/Halloween-HL2-PN-Redux-Original.zip" `
  -ModBaseFilesUrlHash "a47a2cf694c3515171033c0b6ac6797b5825512fd8f891d699a2bc1c261db588" `
  -ModReadmePath "readme.txt" `
  -PublishPath "$PSScriptRoot\..\artifacts\publish"
